### ISSUE TITLE
Hide other nameplates

### ISSUE THREAD

**Issue by Heretic6667** [gtkashi/nameless#3]
Maybe beyond the scope of what you wanted to do with this, but any chance of having the option to add other character names to hide?  Say for example I'm dualboxing- anyway to block myself and my mules names at the same time?

Maybe something like a //nameplate add "CharacterName" kind of thing?

Thx <3

**Comment by gtkashi** [comment]
Indeed, not something I'm likely to try and work out as I don't multi-box beyond having a dummy sit on the lamps in Nyzul. Anyone else is welcome to take this and take a crack at it if they like, but it sounds like it'd be a different type of function entirely. My mind goes back to Witness Protection, which you can edit to not do the randomization and instead find/replace certain names with blanks, but then you're still stuck looking at their linkshells and it mucks with party display. Best of luck.
